#!/bin/bash
echo ruby/rvm/install
SCRIPT_DIR=$( cd "$( dirname "$0" )" && pwd )

if [[ "$(which rvm | wc -l)" == "0" ]]; then
  gpg --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3 2> /dev/null
  curl -sSL https://rvm.io/mpapis.asc | gpg --import - 2> /dev/null
  curl -sSL https://get.rvm.io | bash -s stable --quiet-curl 2> /dev/null
  source "$HOME/.rvm/scripts/rvm"
else
  echo rvm already installed, run "rvm implode" to uninstall
fi
